### ISSUE TITLE
No audio or metadata

### ISSUE THREAD

**Issue by kxkayser** [baudm/mplayer.py#35] opened 2019-01-06 20:26 UTC
Environment:
Raspberry Pi Stretch
Python 3.5.3
MPlayer 1.3.0 (Debian)

I am attempting top use mplayer.py using the python command interface.  

I have not found any documentation as to the actual methods and properties that can be used.

I am able to do a p.loadfile and can print the correct filename and length.  However, I get no audio either via local or HDMI audio devices.,  The file plays fine when using mplayer from the linux command line.  Also, when I try the metadata it seems to return None.  Here is my code:

Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mplayer import Player
>>> p = Player()
>>> p.loadfile('kk.mp3')
>>> print (p.filename)
kk.mp3
>>> print (p.length)
252.0
>>> metadata = p.metadata
>>> print (metadata)
None
>>> print (metadata.get('Title', ''))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'get'
>>>

**Comment by baudm** [comment] 2019-01-09 07:15
Duplicate of #32

**Closed by baudm** 2019-01-09 07:15 UTC
