### ISSUE TITLE
No audio on Raspberry Pi

### ISSUE THREAD

**Issue by kxkayser** [baudm/mplayer.py#36] opened 2019-01-09 01:35 UTC
Well, I solved the errors in my previous post by doing a fresh clone from github and reinstalling.  The pip install doesn't seem to be working.  Now my test program below runs without error and outputs the expected lines.  The only problem is there is NO SOUND from the Raspberry Pi. Have tried both HDMI and Analog audio.  When using mplayer from command line, the audio plays fine  I am running on an RPi 3b+ with latest versions of Linux and Python.  Here is the code:

#!/usr/bin/env python3

from mplayer import Player, CmdPrefix
import time

# Set default prefix for all Player instances
Player.cmd_prefix = CmdPrefix.PAUSING_KEEP

# create Player instance
player = Player()

# Play a file
player.loadfile('/home/pi/Music/dc.mp3')

# Get title from metadata
metadata = player.metadata
print (metadata.get('Artist', ''))
print (metadata.get('Title', ''))

# Print the filename
print (player.filename)

#  Print track length
print(player.length)

Here is the output:
pi@raspberrypi:~/pp $ ./mptest.py
Dixie Chicks
Ready To Run
dc.mp3
232.0
pi@raspberrypi:~/pp $ 

If I could get audio, I could finish this project.  Please help

Thanks,

Ken

**Comment by baudm** [comment] 2019-01-09 07:15
Duplicate of #32

**Closed by baudm** 2019-01-09 07:15 UTC
